spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: dev
  application:
    name: gateway-server-app
  profiles:
    active: path
server:
  port: 8060
